### ISSUE TITLE
关于我

### ISSUE THREAD

**Issue by DCTewi** [DCTewi/dctewi.github.io#2]
https://blog.dctewi.com/post/about/ 

 一个蒟蒻的博客。

**Comment by DCTewi** [comment]
船新版本。
文章会陆续搬过来，主域名当作一个导航页和友链页使用。
评论不知道咋办，就不搬了，从新开始，Rua。

**Comment by ShawnZhou2000** [comment]
乌拉！！

**Comment by DCTewi** [comment]
> @ShawnZhou2000
> 乌拉！！

耶✌

**Comment by daidr** [comment]
新年快乐🎉

**Comment by DCTewi** [comment]
> @daidr 
> 新年快乐🎉

才看到，不好意思哈哈哈哈。
新年快乐!

**Comment by ChenChilde** [comment]
貌似用的Gridea 静态博客~

**Comment by DCTewi** [comment]
> @ChenChilde 
> 貌似用的Gridea 静态博客~

是的，之前用的wp，但是php太费事了
