### ISSUE TITLE
【折腾】Gridea Enchant 总结 | 冻葱Tewi

### ISSUE THREAD

**Issue by DCTewi** [DCTewi/dctewi.github.io#30]
https://blog.dctewi.com/post/gridea-enchant/ 

 一个蒟蒻的博客。

**Comment by sorabug** [comment]
求主题分享

**Comment by QfxL2001** [comment]
谢谢，很有用

**Comment by DCTewi** [comment]
> @sorabug
> 求主题分享

这是Gridea主题商店里买的付费主题，你可以去搜一下

**Comment by DCTewi** [comment]
> @QfxL2001
> 谢谢，很有用

好耶
