### ISSUE TITLE
【算法】正逆康托展开基础 | 冻葱Tewi

### ISSUE THREAD

**Issue by DCTewi** [DCTewi/dctewi.github.io#34]
https://blog.dctewi.com/post/cantor-basic/ 

 一个蒟蒻的博客。

**Comment by Sirlanri** [comment]
网站好漂亮呀！有机会加个友链吧~
https://ri-co.cn

**Comment by DCTewi** [comment]
> @Sirlanri
> 网站好漂亮呀！有机会加个友链吧~
> https://ri-co.cn
> 

才看到不好意思ww，有没有头像地址之类的呀

**Comment by Sirlanri** [comment]
已经加上啦~灰常感谢
等我暑假写完友链页，会回加的_(:з」∠)_
