### ISSUE TITLE
【笔记】在 Blazor WebAssembly Hosted 中使用 Identity | 冻葱Tewi

### ISSUE THREAD

**Issue by DCTewi** [DCTewi/dctewi.github.io#37]
https://blog.dctewi.com/post/blazor-webassembly-hosted-with-identity/ 

 一个蒟蒻的博客。

**Comment by DCTewi** [comment]
大半年没写博客了（

**Comment by lime2008** [comment]
活久见，终于更新了！

**Comment by zhangjinlong1234** [comment]
这是来自二刺猿的程序猿吗

**Comment by DCTewi** [comment]
> @lime2008
> 活久见，终于更新了！

又是半年没更新了，233
