### ISSUE TITLE
【杂谈】重振旗鼓 | 冻葱Tewi

### ISSUE THREAD

**Issue by DCTewi** [DCTewi/dctewi.github.io#38]
https://blog.dctewi.com/post/blog-reboot/ 

 一个蒟蒻的博客。

**Comment by kangyupl** [comment]
一觉醒来，冻葱大佬都快毕业了呢。

**Comment by DCTewi** [comment]
> @kangyupl
> 一觉醒来，冻葱大佬都快毕业了呢。

老了老了，还有三个月）
